# Generated by Django 3.0.7 on 2020-06-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200608_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='Input',
        ),
    ]
