# Generated by Django 3.0.7 on 2020-06-07 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200608_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
