# Generated by Django 3.0.7 on 2020-06-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_input_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='github_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
